# H1 TITLE
## H2 TITLE

In [116]:
print("Buy the dip ?")

Buy the dip ?


In [ ]:
import numpy as np 


#Exercise 1: Your first NumPy array

In [ ]:
mixed_array=np.array([1, #integer
                      2.34, #float
                      "Alex", #String
                      {"key":"value"}, #dictionary
                      ["apple","banana","raspberry"], # list
                      (1,"hello"),# tuple
                      {"apple","banana", "raspberry"}, # a set
                      True], dtype=object)




print(type(mixed_array)) 

for i in mixed_array:
  print(type(i))  

              
                                                    

<class 'numpy.ndarray'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [119]:
#Exercise 2: Zeros
#The question 1 
zero_array = np.zeros(300,dtype=int)
print(zero_array)

count=len(zero_array)
print(count)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]
300


In [120]:
#The question 2 
new_zero_array=zero_array.reshape(3,100)
print(new_zero_array)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [121]:
#Exercise 3: Slicing
#1 Create a NumPy array of dimension 1 that contains all integers from 1 to 100 ordered.
one_array=np.arange(1,101)
print(one_array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [122]:
#2 Without using a for loop and using the array created in Q1, 
# create an array that contain all odd integers.
#odd_array=one_array[one_array%2!=0]

odd_array=one_array[::2]
print(odd_array)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [123]:
#3 Without using a for loop and using the array created in Q1, create an 
# array that contain all even integers reversed. 

even_array=one_array[::-2]
print(even_array)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [124]:
#4 Using array of Q1, set the value of every 3 elements of the list (starting with the second) to 0. 

new_array=one_array

new_array[1::3]=0
print(new_array)

[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


In [125]:
#Exercise 4: Random
#1Set the seed to 888
np.random.seed(888)
#2Generate a one-dimensional array of size 100 with a normal distribution
one_d=np.random.randn(100)
print(one_d)


[ -0.18   0.19   0.83  -0.03  -0.65  -0.11   0.22   0.59   0.10  -1.10
  -0.26   0.41   0.16   1.04   0.22   0.70  -0.87  -1.39  -0.24  -0.76
   1.31  -0.98  -0.36   0.12  -0.35  -0.44  -0.05  -0.43  -1.09  -2.31
  -1.86   0.23  -0.90  -0.54  -0.40   0.02   0.18  -0.57  -0.34  -0.00
   1.45   1.37   2.69   0.68  -1.06   0.13   0.17   0.09   1.04  -0.14
  -0.37   3.20   1.11  -0.26   1.48  -1.57   0.98   1.76   0.35  -0.31
  -1.40  -0.65  -1.38  -0.24  -1.18   0.70   0.28  -1.02   1.10   0.24
  -0.37  -2.20   1.42   0.22   0.79  -0.22  -0.70  -0.92  -1.47   1.88
   1.51   0.12   0.65  -0.71   1.70   1.35   0.53  -0.61  -0.18  -1.29
   1.42  -0.18  -0.10  -0.60   1.20   0.96   0.86   1.96  -1.16   0.35]


In [126]:
#3Generate a two-dimensional array of size 8,8 with random integers from 1 to 10 - both included 
# (same probability for each integer)


two_d= np.random.randint(1,11,(8,8))
print(two_d)

[[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]


In [127]:
#Generate a three-dimensional of size 4,2,5 array with random 
#integers from 1 to 17 - both included (same probability for each integer)
three_d=np.random.randint(1,18,(4,2,5))

print(three_d)

[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]


In [128]:
#Exercise 5: Split, concatenate, reshape arrays

#1 Generate an array with integers from 1 to 50: array([1,...,50])

array=np.arange(1,51)
print(f"Array:{array}")

#2 Generate an array with integers from 51 to 100: array([51,...,100])
array2=np.arange(51,101)
print(f"\nArray2:{array2}")

#3 Using np.concatenate, concatenate the two arrays into: array([1,...,100])

new_array=np.concatenate((array, array2),
axis=0,
out=None,
dtype=None,
)

print(f"\nNew array:{new_array}")

Array:[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Array2:[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]

New array:[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [129]:
#4 Reshape the previous array into:
new_array_sum=new_array.reshape(10,10)
print(new_array_sum)



[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [130]:
#Exercise 6: Broadcasting and Slicing
# 1 Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8.

array_one=np.ones([9,9], dtype=np.int8)
#2 Using slicing, create the following array:
array_one=array_one.astype(np.int8)
array_one[1:-1,1:-1]=0
array_one[2:-2,2:-2]=1
array_one[3:-3,3:-3]=0
array_one[4:-4,4:-4]=1

print(array_one,array_one.dtype)



[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] int8


In [6]:
#3 Using broadcasting create an output matrix based on the following two arrays:
array_1=np.array([1,2,3,4,5])
array_2=np.array([1,2,3])

sub_array1=np.full((9,9),array_1[0])

sub_array2=np.full((9,9),array_1[0])
sub_array2[1:-1,1:-1]=0
sub_array2[2:-2,2:-2]=1
sub_array2[3:-3,3:-3]=0
sub_array2[4:-4,4:-4]=1

sub_array3=np.zeros((5,3),dtype=int)

sub_array3[0,:]=array_2
sub_array3[1,:]=sub_array3[0,:]+array_2
sub_array3[2,:]=sub_array3[1,:]+array_2
sub_array3[3,:]=sub_array3[2,:]+array_2
sub_array3[4,:]=sub_array3[3,:]+array_2


array_3=[sub_array1, sub_array2, sub_array3]

##print(array_3)

for sub_array in array_3:
  
    for row in sub_array:
        print(row.tolist())
    print("]")
    








[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 1, 1, 1, 1, 1, 0, 1]
[1, 0, 1, 0, 0, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 0, 0, 1, 0, 1]
[1, 0, 1, 1, 1, 1, 1, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1]
]
[1, 2, 3]
[2, 4, 6]
[3, 6, 9]
[4, 8, 12]
[5, 10, 15]
]


In [132]:
#Exercise 7: NaN

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
print(grades)

[[  7.00   1.00]
 [   nan   2.00]
 [   nan   8.00]
 [  9.00   3.00]
 [  8.00   9.00]
 [   nan   2.00]
 [  8.00   2.00]
 [   nan   6.00]
 [  9.00   2.00]
 [  8.00   5.00]]


In [133]:

#1 Using np.where, create a third column that takes the grade of the first exam if available; otherwise, it uses the grade from the second exam. 
# Add this column as the third column of the array.
new_vector = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])


grades_with_third_column = np.hstack((grades, new_vector[:, None]))


print(grades_with_third_column)






[[  7.00   1.00   7.00]
 [   nan   2.00   2.00]
 [   nan   8.00   8.00]
 [  9.00   3.00   9.00]
 [  8.00   9.00   8.00]
 [   nan   2.00   2.00]
 [  8.00   2.00   8.00]
 [   nan   6.00   6.00]
 [  9.00   2.00   9.00]
 [  8.00   5.00   8.00]]


In [10]:
# Exercise 8: Wine

#Load the data using genfromtxt, specifying the delimiter as ';', and optimize the numpy array size by reducing the data types. 
#Use np.float32 and verify that the resulting numpy array weighs 76800 bytes.

data=np.genfromtxt('winequality-red.txt',delimiter=";",skip_header=1,dtype=np.float32)

print(data.nbytes)




76752


In [135]:

#2 Display the 2nd, 7th, and 12th rows as a two-dimensional array. Exclude np.nan values if present.


selected_rows =data[[1,6,11],:]

print(selected_rows)


[[  7.80   0.88   0.00   2.60   0.10  25.00  67.00   1.00   3.20   0.68
    9.80   5.00]
 [  7.90   0.60   0.06   1.60   0.07  15.00  59.00   1.00   3.30   0.46
    9.40   5.00]
 [  7.50   0.50   0.36   6.10   0.07  17.00 102.00   1.00   3.35   0.80
   10.50   5.00]]


In [136]:
#3 Determine if there is any wine in the dataset with an alcohol 
#4 Calculate the average alcohol percentage across all wines in the dataset. 
# Exclude np.nan values if present.
# percentage greater than 20%. Return True or False.
alc=data[::,10]
quality=data[::,11]

def percentage_greater_20(alc):
    for a in alc:
        if a>20:
           return True
    return False

print(f"If there is any wine in the dataset with an alcohol percentage greater than 20% - {percentage_greater_20(alc)}")
print(f"Average alcohol percentage across all wines {np.mean(alc)}")






If there is any wine in the dataset with an alcohol percentage greater than 20% - False
Average alcohol percentage across all wines 10.42298412322998


In [137]:
#Compute various statistical measures (minimum, maximum, 25th percentile, 
# 0th percentile, 75th percentile and the mean for the pH values).
ph=data[:,8]

min_ph=np.min(ph)
max_ph=np.max(ph)
percentile_25=np.percentile(ph,25) #Значение, ниже которого находится 25% наблюдений в наборе
percentile_50=np.percentile(ph,50) #Значение, ниже которого находится 50% наблюдений в наборе
percentile_75=np.percentile(ph,75) #Значение, ниже которого находится 75% наблюдений в наборе
mean_PH_values=np.mean(ph)


print("Percentile 25% PH ", percentile_25)
print("Percentile 50% PH ", percentile_50)
print("Percentile 75% PH ", percentile_75)
print("Mean PH ", mean_PH_values)

print("Minimum PH ", min_ph)
print("Maximum PH ", max_ph)

Percentile 25% PH  3.21
Percentile 50% PH  3.31
Percentile 75% PH  3.4
Mean PH  3.3111134
Minimum PH  2.74
Maximum PH  4.01


In [138]:

#6 Find the average quality score of wines with 
# the 20% least sulphate content.
sulfate=data[:,9]
quality=data[:,11]
sulf_percentile_20=np.percentile(sulfate,20)

low_suf_mask=sulfate<sulf_percentile_20

quality_low_sulphates=quality[low_suf_mask]

mean_quality_low_sulf=np.mean(quality_low_sulphates)



print("Quality of wines with low sulfate content:",mean_quality_low_sulf)

print("20th percentile for sulfates:",sulf_percentile_20)




Quality of wines with low sulfate content: 5.1854305
20th percentile for sulfates: 0.54


In [139]:
#Compute the mean of all variables for wines with 
# the best quality. Also, do the same for wines with the worst quality.

import numpy as np


quality = data[:, 11]  
max_quality = np.max(quality)
min_quality = np.min(quality)

# Создаем маски для вин с лучшим и худшим качеством
high_quality_mask = quality == max_quality
low_quality_mask = quality == min_quality

high_quality_wines = data[high_quality_mask]
low_quality_wines = data[low_quality_mask]



# Вычисляем средние значения для вин с лучшим и худшим качеством
high_quality_mean = np.mean(high_quality_wines, axis=0)
low_quality_mean = np.mean(low_quality_wines, axis=0)

print("Mean for vines with best quality:", high_quality_mean)
print("Mean for vines with worst quality:", low_quality_mean)





Mean for vines with best quality: [  8.57   0.42   0.39   2.58   0.07  13.28  33.44   1.00   3.27   0.77
  12.09   8.00]
Mean for vines with worst quality: [  8.36   0.88   0.17   2.64   0.12  11.00  24.90   1.00   3.40   0.57
   9.95   3.00]


In [141]:
import numpy as np
import itertools

def load_data(file_path):
    """ Загружает матрицу предсказаний разницы очков между командами """
    def nan_converter(value):
        return 0.0 if value == 'nan' else float(value)
    
    with open(file_path, 'r') as file:
        data = np.loadtxt(file, delimiter=',', converters={i: nan_converter for i in range(10)})
    return data

def find_optimal_pairing(score_matrix):
    """ Находит разбиение на пары, минимизирующее сумму квадратов разниц очков """
    teams = np.arange(len(score_matrix))
    min_score = float('inf')
    best_pairing = None

    # Генерируем всевозможные перестановки
    for perm in itertools.permutations(teams):
        pairing = np.array(perm).reshape(2, -1)  # Преобразуем в (2, 5)
        score_diffs = score_matrix[pairing[0], pairing[1]]
        total_score = np.sum(score_diffs**2)  # Сумма квадратов разниц

        if total_score < min_score:
            min_score = total_score
            best_pairing = pairing

    return best_pairing

def main():
    data = load_data('model_forecasts.txt')
    optimal_pairs = find_optimal_pairing(data)
    print("Оптимальное разбиение:")
    print(optimal_pairs)

if __name__ == "__main__":
    main()


Оптимальное разбиение:
[[0 1 2 3 5]
 [8 7 9 4 6]]
